version: "3.3"

services:
  app:
    build: .
    command: bash start.sh
    restart: on-failure
    ports:
      - "126:126"
      - "4386:4386"
networks:
  default:
    external: true
    name: network7